# Map model to languages.
# It is assumed that a model can translate between any of the languages given
# below.
# Use two letter language codes everywhere.
models:
  # The order of models has meaning. The should be listed in the
  # decreasing order of preference.
  # When a language has multiple models, language specific model mapping
  # would be checked as first step. If not, models listed here would be
  # tried. The first model that matches for the pair would be the default
  # model for the language pair.
  indictrans2-indic-indic:
    - as
    - bn
    - brx
    - doi
    - gom
    - gu
    - hi
    - kn
    - ks
    - mai
    - ml
    - mni
    - mr
    - ne
    - or
    - pa
    - sa
    - sat
    # - sd Sindhi uses Arabic script in Wikipedia. Current model does not support it.
    - ta
    - te
    - ur

  nllb200-600M:
    - ace
    - acm
    - acq
    - aeb
    - af
    - ajp
    - ak
    - am
    - apc
    - ar
    - ars
    - ary
    - arz
    - as
    - ast
    - awa
    - az
    - azb
    - ba
    - ban
    - be
    - bem
    - bg
    - bh
    - bjn
    - bm
    - bn
    - bo
    - bs
    - bug
    - ca
    - ceb
    - cjk
    - ckb
    - crh
    - cs
    - cy
    - da
    - de
    - din
    - dyu
    - dz
    - ee
    - el
    - en
    - eo
    - es
    - et
    - eu
    - fa
    - ff
    - fi
    - fj
    - fo
    - fon
    - fr
    - fur
    - ga
    - gan
    - gd
    - gl
    - gn
    - gu
    - ha
    - he
    - hi
    - hne
    - hr
    - ht
    - hu
    - hy
    - id
    - ig
    - ilo
    - is
    - it
    - ja
    - jv
    - ka
    - kab
    - kac
    - kam
    - kbp
    - kea
    - kg
    - ki
    - kk
    - km
    - kmb
    - kn
    - knc
    - ko
    - kr
    - ks
    - ku
    - ky
    - lb
    - lg
    - li
    - lij
    - lmo
    - ln
    - lo
    - lt
    - ltg
    - lua
    - luo
    - lus
    - lv
    - mag
    - mai
    - mg
    - mi
    - min
    - mk
    - ml
    - mn
    - mni
    - mos
    - mr
    - ms
    - mt
    - my
    - ne
    - nl
    - nn
    - "no"
    - nso
    - nus
    - ny
    - oc
    - om
    - or
    - pa
    - pag
    - pap
    - pl
    - ps
    - pt
    - qu
    - rn
    - ro
    - ru
    - rw
    - sa
    - sc
    - scn
    - sd
    - sg
    - shn
    - si
    - sk
    - sl
    - sm
    - sn
    - so
    - sq
    - sr
    - ss
    - st
    - su
    - sv
    - sw
    - szl
    - ta
    - taq
    - te
    - tg
    - th
    - ti
    - tk
    - tl
    - tn
    - tpi
    - tr
    - ts
    - tt
    - tum
    - tw
    - tzm
    - ug
    - uk
    - umb
    - ur
    - uz
    - vec
    - vi
    - war
    - wo
    - xh
    - yi
    - yo
    - zh
    - zu
  opusmt-sv-fi:
    - sv
    - fi
  # MADLAD-400 is a fallback model. It has relatively low quality, but wider language coverage
  # If there is no other models, this model will be used.
  madlad-400:
    - ady # Adyghe
    - alt # Southern Altai
    - an  # Aragonese
    - ang # Old English
    - av  # Avar
    - bar # Bavarian (bar)
    - bi  # Bislama
    - br  # Breton
    - ce  # Chechen
    - ch  # Chamorro
    - cr  # Cree
    - en  # English
    - simple # Simple English (simple)
    - frp # Arpitan
    - gag # Gagauz
    - gor # Gorontalo
    - gv  # Manx
    - hif # Fiji Hindi
    - io  # Ido
    - iu  # Inuktitut
    - jam # Jamaican Creole English
    - kaa # Kara-Kalpak
    - kbd # Kabardian
    - kl  # Kalaallisut
    - koi # Komi-Permyak
    - krc # Karachay-Balkar
    - kv  # Komi
    - kw  # Cornish
    - mad # Madurese
    - mdf # Moksha
    - mnw # Mon
    - mwl # Mirandese
    - myv # Erzya
    - nds # Low German
    - nds-nl # Low Saxon
    - new # Newari
    - nia # Nias
    - nv  # Navajo
    - os  # Ossetic
    - pam # Pampanga
    - rm  # Romansh
    - se  # Northern Sami
    - sh  # Serbo-Croatian
    - skr # Saraiki
    - srn # Sranan Tongo
    - stq # Saterland Frisian
    - tcy # Tulu
    - tet # Tetum
    - tly # Talysh
    - tyv # Tuvinian
    - ve  # Venda
    - wa  # Walloon
    - wuu # Wu Chinese
    - xal # Kalmyk
    - zh-min-nan # Nan
    - zh-yue # Cantonese

# Map languages to model.
languages:
  as:
    - en: indictrans2-indic-en
  bn:
    - en: indictrans2-indic-en
  brx:
    - en: indictrans2-indic-en
  ca:
    - de: softcatala-ca-de
    - es: softcatala-ca-es
    - en: softcatala-ca-en
    - fr: softcatala-ca-fr
    - gl: softcatala-ca-gl
    - it: softcatala-ca-it
    - ja: softcatala-ca-ja
    - nl: softcatala-ca-nl
    - oc: softcatala-ca-oc
    - pt: softcatala-ca-pt
  de:
    - ca: softcatala-de-ca
  doi:
    - en: indictrans2-indic-en
  en:
    - as: indictrans2-en-indic
    - ast: nllb-wikipedia
    - ay: nllb-wikipedia
    - ba: nllb-wikipedia
    - bcl: opusmt-en-bcl
    - bi: opusmt-en-bi
    - bn: indictrans2-en-indic
    - brx: indictrans2-en-indic  # Bodo
    - ca: softcatala-en-ca
    - chr: opusmt-en-chr
    - ckb: nllb-wikipedia
    - doi: indictrans2-en-indic  # Dogri
    - gom: indictrans2-en-indic
    - guw: opusmt-en-guw
    - gu: indictrans2-en-indic
    - ha: nllb-wikipedia
    - hi: indictrans2-en-indic
    - ig: nllb-wikipedia
    - ilo: nllb-wikipedia
    - is: nllb-wikipedia
    - kg: nllb-wikipedia
    - kn: indictrans2-en-indic
    - ks: indictrans2-en-indic
    - lg: nllb-wikipedia
    - ln: nllb-wikipedia
    - mai: indictrans2-en-indic
    - ml: indictrans2-en-indic
    - mni: indictrans2-en-indic
    - mr: indictrans2-en-indic
    - ne: indictrans2-en-indic
    - nso: nllb-wikipedia
    - oc: nllb-wikipedia
    - om: nllb-wikipedia
    - or: indictrans2-en-indic
    - pa: indictrans2-en-indic
    - sa: indictrans2-en-indic
    - sat: indictrans2-en-indic
    - sd: indictrans2-en-indic
    - srn: opusmt-en-srn
    - ss: nllb-wikipedia
    - ta: indictrans2-en-indic
    - te: indictrans2-en-indic
    - tn: nllb-wikipedia
    - to: opusmt-en-to
    - ty: opusmt-en-ty
    - ts: nllb-wikipedia
    - ur: indictrans2-en-indic
    - ve: opusmt-en-ve
    - wo: nllb-wikipedia
    - zh: nllb-wikipedia
    - zu: nllb-wikipedia
  es:
    - as: nllb-wikipedia
    - ast: nllb-wikipedia
    - ay: nllb-wikipedia
    - ba: nllb-wikipedia
    - ckb: nllb-wikipedia
    - ha: nllb-wikipedia
    - ig: nllb-wikipedia
    - ilo: nllb-wikipedia
    - is: nllb-wikipedia
    - kg: nllb-wikipedia
    - ln: nllb-wikipedia
    - lg: nllb-wikipedia
    - nso: nllb-wikipedia
    - oc: nllb-wikipedia
    - om: nllb-wikipedia
    - ss: nllb-wikipedia
    - ti: nllb-wikipedia
    - tn: nllb-wikipedia
    - ts: nllb-wikipedia
    - zh: nllb-wikipedia
    - zu: nllb-wikipedia
  fi:
      - sv: nllb200-600M
  fr:
    - as: nllb-wikipedia
    - ast: nllb-wikipedia
    - ay: nllb-wikipedia
    - ba: nllb-wikipedia
    - ca: softcatala-fr-ca
    - ckb: nllb-wikipedia
    - ha: nllb-wikipedia
    - ig: nllb-wikipedia
    - ilo: nllb-wikipedia
    - is: nllb-wikipedia
    - kg: nllb-wikipedia
    - ln: nllb-wikipedia
    - lg: nllb-wikipedia
    - nso: nllb-wikipedia
    - oc: nllb-wikipedia
    - om: nllb-wikipedia
    - ss: nllb-wikipedia
    - ti: nllb-wikipedia
    - tn: nllb-wikipedia
    - ts: nllb-wikipedia
    - ty: opusmt-fr-ty
    - wo: nllb-wikipedia
    - zh: nllb-wikipedia
    - zu: nllb-wikipedia
  gl:
    - ca: softcatala-gl-ca
  gom:
    - en: indictrans2-indic-en
  gu:
    - en: indictrans2-indic-en
  hi:
    - en: indictrans2-indic-en
  it:
    - ca: softcatala-ti-ca
  ja:
    - ca: softcatala-ja-ca
  kn:
    - en: indictrans2-indic-en
  ks:
    - en: indictrans2-indic-en
  mai:
    - en: indictrans2-indic-en
  ml:
    - en: indictrans2-indic-en
  mr:
    - en: indictrans2-indic-en
  mni:
    - en: indictrans2-indic-en
  ne:
    - en: indictrans2-indic-en
  nl:
    - ca: softcatala-nl-ca
  or:
    - en: indictrans2-indic-en
  pa:
    - en: indictrans2-indic-en
  pt:
    - oc: nllb-wikipedia
    - ca: softcatala-pt-ca
  sa:
    - en: indictrans2-indic-en
  sat:
    - en: indictrans2-indic-en
  sd:
    - en: indictrans2-indic-en
  ru:
    - ba: nllb-wikipedia
  ta:
    - en: indictrans2-indic-en
  te:
    - en: indictrans2-indic-en
  ur:
    - en: indictrans2-indic-en
