# Map model to languages.
# It is assumed that a model can translate between any of the languages given below
# Use two letter language codes everywhere.
models:
  nllb200-600M:
  - ace
  - acm
  - acq
  - aeb
  - af
  - ajp
  - ak
  - am
  - ar
  - ary
  - arz
  - as
  - ast
  - awa
  - az
  - azb
  - ba
  - ban
  - be
  - bem
  - bg
  - bh
  - bjn
  - bm
  - bn
  - bo
  - bs
  - bug
  - ca
  - ceb
  - cjk
  - ckb
  - crh
  - cs
  - cy
  - da
  - de
  - din
  - dyu
  - dz
  - ee
  - el
  - en
  - eo
  - es
  - et
  - eu
  - fa
  - ff
  - fi
  - fj
  - fo
  - fon
  - fr
  - fur
  - ga
  - gd
  - gl
  - gn
  - gu
  - ha
  - he
  - hi
  - hne
  - hr
  - ht
  - hu
  - hy
  - id
  - ig
  - ilo
  - is
  - it
  - ja
  - jv
  - ka
  - kab
  - kac
  - kam
  - kbp
  - kea
  - kg
  - ki
  - kk
  - km
  - kmb
  - kn
  - knc
  - ko
  - ks
  - ku
  - ky
  - lb
  - lg
  - li
  - lij
  - lmo
  - ln
  - lo
  - lt
  - ltg
  - lua
  - luo
  - lus
  - lv
  - mag
  - mai
  - mg
  - mi
  - min
  - mk
  - ml
  - mn
  - mni
  - mos
  - mr
  - ms
  - mt
  - my
  - nb
  - ne
  - nl
  - nn
  - nso
  - nus
  - ny
  - oc
  - om
  - or
  - pa
  - pag
  - pap
  - pl
  - ps
  - pt
  - qu
  - rn
  - ro
  - ru
  - rw
  - sa
  - sat
  - sc
  - scn
  - sd
  - sg
  - shn
  - si
  - sk
  - sl
  - sm
  - sn
  - so
  - sq
  - sr
  - ss
  - st
  - su
  - sv
  - sw
  - szl
  - ta
  - taq
  - te
  - tg
  - th
  - ti
  - tk
  - tl
  - tn
  - tpi
  - tr
  - ts
  - tt
  - tum
  - tw
  - tzm
  - ug
  - uk
  - umb
  - ur
  - uz
  - vec
  - vi
  - war
  - wo
  - xh
  - yi
  - yo
  - zh
  - zu

# Map languages to model.
languages:
  en:
    - as: nllb-wikipedia
    - ast: nllb-wikipedia
    - ay: nllb-wikipedia
    - ba: nllb-wikipedia
    - bcl: opusmt
    - ckb: nllb-wikipedia
    - ha: nllb-wikipedia
    - ig: nllb-wikipedia
    - ilo: nllb-wikipedia
    - is: nllb-wikipedia
    - kg: nllb-wikipedia
    - ln: nllb-wikipedia
    - lg: nllb-wikipedia
    - nso: nllb-wikipedia
    - oc: nllb-wikipedia
    - om: nllb-wikipedia
    - ss: nllb-wikipedia
    - tn: nllb-wikipedia
    - ts: nllb-wikipedia
    - wo: nllb-wikipedia
    - zh: nllb-wikipedia
    - zu: nllb-wikipedia
  ca:
    - oc: nllb-wikipedia
  es:
    - as: nllb-wikipedia
    - ast: nllb-wikipedia
    - ay: nllb-wikipedia
    - ba: nllb-wikipedia
    - ckb: nllb-wikipedia
    - ha: nllb-wikipedia
    - ig: nllb-wikipedia
    - ilo: nllb-wikipedia
    - is: nllb-wikipedia
    - kg: nllb-wikipedia
    - ln: nllb-wikipedia
    - lg: nllb-wikipedia
    - nso: nllb-wikipedia
    - oc: nllb-wikipedia
    - om: nllb-wikipedia
    - ss: nllb-wikipedia
    - ti: nllb-wikipedia
    - tn: nllb-wikipedia
    - ts: nllb-wikipedia
    - zh: nllb-wikipedia
    - zu: nllb-wikipedia
  fr:
    - as: nllb-wikipedia
    - ast: nllb-wikipedia
    - ay: nllb-wikipedia
    - ba: nllb-wikipedia
    - ckb: nllb-wikipedia
    - ha: nllb-wikipedia
    - ig: nllb-wikipedia
    - ilo: nllb-wikipedia
    - is: nllb-wikipedia
    - kg: nllb-wikipedia
    - ln: nllb-wikipedia
    - lg: nllb-wikipedia
    - nso: nllb-wikipedia
    - oc: nllb-wikipedia
    - om: nllb-wikipedia
    - ss: nllb-wikipedia
    - ti: nllb-wikipedia
    - tn: nllb-wikipedia
    - ts: nllb-wikipedia
    - wo: nllb-wikipedia
    - zh: nllb-wikipedia
    - zu: nllb-wikipedia
  pt:
    - oc: nllb-wikipedia
  ru:
    - ba: nllb-wikipedia
