# Map model to languages.
# It is assumed that a model can translate between any of the languages given
# below.
# Use two letter language codes everywhere.
models:
  nllb200-600M:
    - ace
    - acm
    - acq
    - aeb
    - af
    - ajp
    - ak
    - am
    - apc
    - ar
    - ars
    - ary
    - arz
    - as
    - ast
    - awa
    - az
    - azb
    - ba
    - ban
    - be
    - bem
    - bg
    - bh
    - bjn
    - bm
    - bn
    - bo
    - bs
    - bug
    - ca
    - ceb
    - cjk
    - ckb
    - crh
    - cs
    - cy
    - da
    - de
    - din
    - dyu
    - dz
    - ee
    - el
    - en
    - eo
    - es
    - et
    - eu
    - fa
    - ff
    - fi
    - fj
    - fo
    - fon
    - fr
    - fur
    - ga
    - gan
    - gd
    - gl
    - gn
    - gu
    - ha
    - he
    - hi
    - hne
    - hr
    - ht
    - hu
    - hy
    - id
    - ig
    - ilo
    - is
    - it
    - ja
    - jv
    - ka
    - kab
    - kac
    - kam
    - kbp
    - kea
    - kg
    - ki
    - kk
    - km
    - kmb
    - kn
    - knc
    - ko
    - kr
    - ks
    - ku
    - ky
    - lb
    - lg
    - li
    - lij
    - lmo
    - ln
    - lo
    - lt
    - ltg
    - lua
    - luo
    - lus
    - lv
    - mag
    - mai
    - mg
    - mi
    - min
    - mk
    - ml
    - mn
    - mni
    - mos
    - mr
    - ms
    - mt
    - my
    - ne
    - nl
    - nn
    - "no"
    - nso
    - nus
    - ny
    - oc
    - om
    - or
    - pa
    - pag
    - pap
    - pl
    - ps
    - pt
    - qu
    - rn
    - ro
    - ru
    - rw
    - sa
    - sc
    - scn
    - sd
    - sg
    - shn
    - si
    - sk
    - sl
    - sm
    - sn
    - so
    - sq
    - sr
    - ss
    - st
    - su
    - sv
    - sw
    - szl
    - ta
    - taq
    - te
    - tg
    - th
    - ti
    - tk
    - tl
    - tn
    - tpi
    - tr
    - ts
    - tt
    - tum
    - tw
    - tzm
    - ug
    - uk
    - umb
    - ur
    - uz
    - vec
    - vi
    - war
    - wo
    - xh
    - yi
    - yo
    - zh
    - zu

  indictrans2-indic-indic:
    - as
    - bn
    - brx
    - doi
    - gom
    - gu
    - hi
    - kn
    - ks
    - mai
    - ml
    - mni
    - mr
    - ne
    - or
    - pa
    - sa
    - sat
    # - sd Sindhi uses Arabic script in Wikipedia. Current model does not support it.
    - ta
    - te
    - ur

  madlad-400:
    - ace
    - ace_Arab
    - af
    - am
    - an
    - ar
    - ary
    - arz
    - as
    - az
    - ba
    - ban
    - bar
    - be
    - bg
    - bho
    - bjn
    - bjn_Arab
    - bm
    - bn
    - br
    - bs
    - bug
    - ca
    - ceb
    - crh_Latn
    - cs
    - cy
    - da
    - de
    - din
    - dv
    - dz
    - el
    - en
    - eo
    - es
    - et
    - eu
    - fa
    - fi
    - fo
    - fr
    - fr_CA
    - fur
    - fuv
    - fy
    - ga
    - gd
    - gl
    - gn
    - gu
    - ha
    - he
    - hi
    - hne
    - hr
    - hu
    - hy
    - id
    - ig
    - io
    - is
    - it
    - iu
    - ja
    - jv
    - ka
    - kk
    - km
    - kn
    - ko
    - kr
    - kr_Arab
    - ks
    - ks_Deva
    - ku
    - ky
    - la
    - lb
    - li
    - lij
    - lmo
    - lt
    - ltg
    - lv
    - mag
    - mg
    - mi
    - mk
    - ml
    - mn
    - mni
    - mr
    - ms
    - mt
    - mwl
    - my
    - nds
    - nds_NL
    - ne
    - nl
    - nn
    - "no"
    - nus
    - oc
    - or
    - pa
    - pl
    - prs
    - ps
    - pt
    - ro
    - ru
    - rw
    - sc
    - scn
    - sd
    - se
    - sh
    - shn
    - si
    - en_xx_simple
    - sk
    - sl
    - so
    - sq
    - sr
    - sv
    - sw
    - szl
    - ta
    - taq
    - taq_Tfng
    - te
    - tg
    - th
    - tk
    - fil
    - tr
    - tt
    - tzm
    - ug
    - uk
    - ur
    - uz
    - vec
    - vi
    - wa
    - wuu
    - xh
    - yi
    - yo
    - zh
    - zh_Hant
    - zu
    - abt
    - acf
    - ada
    - adh
    - ady
    - agr
    - ahk
    - ak
    - akb
    - alt
    - alz
    - amu
    - ang
    - ann
    - ape
    - arn
    - av
    - awa
    - ay
    - az_RU
    - bas
    - bbc
    - bci
    - ber
    - ber_Latn
    - bew
    - bg_Latn
    - bgp
    - bi
    - bik
    - bim
    - bn_Latn
    - bo
    - bqc
    - bru
    - brx
    - bts
    - btx
    - bua
    - bus
    - bzj
    - cab
    - cac
    - cak
    - cbk
    - cce
    - ce
    - cfm
    - ch
    - chk
    - chm
    - chr
    - ckb
    - cnh
    - co
    - cr_Latn
    - crh
    - crs
    - ctd_Latn
    - ctu
    - cuk
    - cv
    - dje
    - djk
    - dln
    - doi
    - dov
    - dtp
    - zxx_xx_dtynoise
    - dwr
    - dyu
    - ee
    - el_Latn
    - emp
    - enq
    - bum
    - ff
    - ffm
    - fip
    - fj
    - fon
    - frp
    - gag
    - gbm
    - gof
    - gom
    - gom_Latn
    - gor
    - grc
    - gsw
    - gu_Latn
    - gub
    - guc
    - guh
    - gui
    - gv
    - gvl
    - gym
    - haw
    - hi_Latn
    - hif
    - hil
    - hmn
    - ho
    - ht
    - hui
    - hus
    - hvn
    - iba
    - ibb
    - ify
    - ilo
    - inb
    - iso
    - ium
    - izz
    - jac
    - jam
    - jiv
    - jvn
    - kaa
    - kaa_Latn
    - kac
    - kbd
    - kbp
    - kek
    - kg
    - kha
    - kj
    - kjg
    - kjh
    - kl
    - kmb
    - kmz_Latn
    - kn_Latn
    - knj
    - koi
    - kos
    - krc
    - kri
    - ksd
    - ksw
    - ktu
    - kum
    - kv
    - kw
    - kwi
    - laj
    - lg
    - lhu
    - ln
    - lo
    - lrc
    - lu
    - lus
    - mad
    - mai
    - mak
    - mam
    - mas
    - maz
    - mbt
    - mdf
    - meo
    - meu
    - mfe
    - mgh
    - mh
    - min
    - miq
    - mkn
    # - ml_Latn
    - mps
    - mqy
    - mrj
    - mrw
    - ms_Arab
    - ms_Arab_BN
    - msb
    - msi
    - msm
    - myv
    - nan_Latn_TW
    - ndc_ZW
    - new
    - ngu
    - nhe
    - nia
    - nij
    - niq
    - nnb
    - noa
    - nog
    - nr
    - nso
    - nut
    - nv
    - ny
    - nyu
    - nzi
    - oj
    - om
    - os
    - otq
    - pag
    - pap
    - pau
    - pck
    - pis
    - pon
    - ppk
    - qu
    - qub
    - quc
    - quf
    - quh
    - qup
    - quy
    - qvc
    - qvi
    - qvz
    - qxr
    - raj
    - rcf
    - rki
    - rm
    - rmc
    - rn
    - rom
    - ru_Latn
    - rwo
    - sa
    - sah
    - sat_Latn
    - sda
    - seh
    - sg
    - shp
    - sja
    - skr
    - sm
    - smt
    - sn
    - spp
    - srm
    - srn
    - ss
    - st
    - stq
    - su
    - sus
    - suz
    - sxn
    - syr
    - ta_Latn
    - tab
    - taj
    - tbz
    - tca
    - tcy
    - tdx
    - te_Latn
    - teo
    - tet
    - ti
    - tiv
    - tks
    - tlh
    - tll
    - tly_IR
    - tn
    - to
    - toj
    - trp
    - ts
    - tsc
    - tsg
    - tuc
    - tvl
    - twu
    - tyv
    - tyz
    - tzh
    - tzj
    - tzo
    - ubu
    - udm
    - ve
    - wal
    - war
    - wo
    - xal
    - yap
    - yua
    - zap
    - zh_Latn
    - zne
    - zza

# Map languages to model.
languages:
  as:
    - en: indictrans2-indic-en
  bn:
    - en: indictrans2-indic-en
  brx:
    - en: indictrans2-indic-en
  ca:
    - oc: nllb-wikipedia
  doi:
    - en: indictrans2-indic-en
  en:
    - as: indictrans2-en-indic
    - ast: nllb-wikipedia
    - ay: nllb-wikipedia
    - ba: nllb-wikipedia
    - bcl: opusmt-en-bcl
    - bi: opusmt-en-bi
    - bn: indictrans2-en-indic
    - brx: indictrans2-en-indic  # Bodo
    - ca: softcatala
    - chr: opusmt-en-chr
    - ckb: nllb-wikipedia
    - doi: indictrans2-en-indic  # Dogri
    - gom: indictrans2-en-indic
    - guw: opusmt-en-guw
    - gu: indictrans2-en-indic
    - ha: nllb-wikipedia
    - hi: indictrans2-en-indic
    - ig: nllb-wikipedia
    - ilo: nllb-wikipedia
    - is: nllb-wikipedia
    - kg: nllb-wikipedia
    - kn: indictrans2-en-indic
    - ks: indictrans2-en-indic
    - lg: nllb-wikipedia
    - ln: nllb-wikipedia
    - mai: indictrans2-en-indic
    - ml: indictrans2-en-indic
    - mni: indictrans2-en-indic
    - mr: indictrans2-en-indic
    - ne: indictrans2-en-indic
    - nso: nllb-wikipedia
    - oc: nllb-wikipedia
    - om: nllb-wikipedia
    - or: indictrans2-en-indic
    - pa: indictrans2-en-indic
    - sa: indictrans2-en-indic
    - sat: indictrans2-en-indic
    - sd: indictrans2-en-indic
    - srn: opusmt-en-srn
    - ss: nllb-wikipedia
    - ta: indictrans2-en-indic
    - te: indictrans2-en-indic
    - tn: nllb-wikipedia
    - to: opusmt-en-to
    - ty: opusmt-en-ty
    - ts: nllb-wikipedia
    - ur: indictrans2-en-indic
    - ve: opusmt-en-ve
    - wo: nllb-wikipedia
    - zh: nllb-wikipedia
    - zu: nllb-wikipedia
  es:
    - as: nllb-wikipedia
    - ast: nllb-wikipedia
    - ay: nllb-wikipedia
    - ba: nllb-wikipedia
    - ckb: nllb-wikipedia
    - ha: nllb-wikipedia
    - ig: nllb-wikipedia
    - ilo: nllb-wikipedia
    - is: nllb-wikipedia
    - kg: nllb-wikipedia
    - ln: nllb-wikipedia
    - lg: nllb-wikipedia
    - nso: nllb-wikipedia
    - oc: nllb-wikipedia
    - om: nllb-wikipedia
    - ss: nllb-wikipedia
    - ti: nllb-wikipedia
    - tn: nllb-wikipedia
    - ts: nllb-wikipedia
    - zh: nllb-wikipedia
    - zu: nllb-wikipedia
  fr:
    - as: nllb-wikipedia
    - ast: nllb-wikipedia
    - ay: nllb-wikipedia
    - ba: nllb-wikipedia
    - ckb: nllb-wikipedia
    - ha: nllb-wikipedia
    - ig: nllb-wikipedia
    - ilo: nllb-wikipedia
    - is: nllb-wikipedia
    - kg: nllb-wikipedia
    - ln: nllb-wikipedia
    - lg: nllb-wikipedia
    - nso: nllb-wikipedia
    - oc: nllb-wikipedia
    - om: nllb-wikipedia
    - ss: nllb-wikipedia
    - ti: nllb-wikipedia
    - tn: nllb-wikipedia
    - ts: nllb-wikipedia
    - wo: nllb-wikipedia
    - zh: nllb-wikipedia
    - zu: nllb-wikipedia
  gom:
    - en: indictrans2-indic-en
  gu:
    - en: indictrans2-indic-en
  hi:
    - en: indictrans2-indic-en
  kn:
    - en: indictrans2-indic-en
  ks:
    - en: indictrans2-indic-en
  mai:
    - en: indictrans2-indic-en
  ml:
    - en: indictrans2-indic-en
  mr:
    - en: indictrans2-indic-en
  mni:
    - en: indictrans2-indic-en
  ne:
    - en: indictrans2-indic-en
  or:
    - en: indictrans2-indic-en
  pa:
    - en: indictrans2-indic-en
  pt:
    - oc: nllb-wikipedia
  sa:
    - en: indictrans2-indic-en
  sat:
    - en: indictrans2-indic-en
  sd:
    - en: indictrans2-indic-en
  ru:
    - ba: nllb-wikipedia
  ta:
    - en: indictrans2-indic-en
  te:
    - en: indictrans2-indic-en
  ur:
    - en: indictrans2-indic-en
