[build-system]
requires = ["setuptools", "wheel", "hatchling"]
build-backend = "hatchling.build"

[project]
name = "machinetranslation"
classifiers = ["Private :: Do Not Upload"]
version = "0"
requires-python = ">=3.9"
dependencies = [
    "ctranslate2",
    "sentencepiece",
    "Flask",
    "gunicorn",
    "statsd",
    "ecs-logging"
]

[project.optional-dependencies]
tests = [
    'pytest'
]
