[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "machinetranslation"
classifiers = ["Private :: Do Not Upload"]
version = "0"
dependencies = ["ctranslate2", "sentencepiece", "Flask", "gunicorn"]
