openapi: 3.0.1
info:
  version: 0.2.1
  title: Machine translation service
  description: Machine translation service for translating content between languages.
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  contact:
    name: the Wikimedia Language team
    url: https://www.mediawiki.org/wiki/Wikimedia_Language_engineering
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT

paths:
  /:
    get:
      tags:
        - Root
      description: The root service end-point
      responses:
        "200":
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
      x-amples:
        - title: spec from root
          request:
            query:
              spec: true
          response:
            status: 200
  /translate/{from}/{to}:
    post:
      tags:
        - Machine translation
      description: Fetches the machine translation. Some providers require an authorization header and it is forbidden to use them outside the Content Translation tool.
      parameters:
        - $ref: "#/components/parameters/from"
        - $ref: "#/components/parameters/to"
      requestBody:
        content:
          application/json:
            schema:
              required:
                - html
              properties:
                html:
                  type: string
                  description: The HTML content to translate
                  x-textarea: true
        required: true
      responses:
        "200":
          description: Machine translation fetched successfully
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Internal error
          content: {}
      x-amples:
        - title: Machine translate.
          request:
            params:
              from: en
              to: ig
            body:
              html: Oxygen is a chemical element with symbol O and atomic number 8
          response:
            status: 200
            body:
              contents: /.+/
            headers:
              content-type: application/json

  /languages:
    get:
      tags:
        - Tools
      description: Lists all languages supported
      responses:
        "200":
          description: Lists the tools for a given language pair fetched successfully
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Internal error
          content: {}

components:
  schemas:
    # A https://tools.ietf.org/html/draft-nottingham-http-problem
    problem:
      required:
        - type
      properties:
        status:
          type: integer
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        method:
          type: string
        uri:
          type: string
  parameters:
    from:
      name: from
      in: path
      description: The source language code
      schema:
        type: string
      required: true
    to:
      name: to
      in: path
      description: The target language code
      schema:
        type: string
      required: true

